#!/usr/bin/env bash
set -euo pipefail

while 

record() {
    while true {
        adb shell screenrecord /sdcard/patrol.mp4 --time-limit 10 &
        # echo $! > "$HOME/screenrecord.pid"
        lsof -p $pid +r 1 &>/dev/null # wait
    }

}

# put a function in the background
name &

# do something
