#!/usr/bin/env bash

DIFF="diff"
if command -v delta >/dev/null 2>&1; then
  DIFF="delta"
fi

total=0
passed=0
for file_in in examples/*.in; do
    base_name="${file_in%.in}"
    file_out="${base_name}.out"
    GREEN='\033[0;32m'
    RED='\033[0;31m'
    NC='\033[0m'
    if $DIFF <(./main < "$file_in") "$file_out"
    then
        echo -e "${GREEN}Test $base_name passed${NC}"
        passed=$((passed + 1))
    else
        echo -e "${RED}Test $base_name failed${NC}"
    fi
    total=$((total + 1))
done

printf "%d / %d tests passed\n" "$passed" "$total"
