#!/usr/bin/env bash


for file_in in examples/*.in; do
    base_name="${file_in%.in}"
    file_out="${base_name}.out"
    # echo "===> ${base_name}"
    GREEN='\033[0;32m'
    RED='\033[0;31m'
    NC='\033[0m'
    if diff <(./main < "$file_in") "$file_out" >/dev/null
    then
        echo -e "${GREEN}Test $base_name passed${NC}"
    else
        echo -e "${RED}Test $base_name failed${NC}"
    fi
done
