services:
  db:
    image: postgis/postgis:17-3.5-alpine # Postgres 17, PostGIS 3.5
    container_name: postgis_db
    environment:
      POSTGRES_USER: osm_user
      POSTGRES_PASSWORD: osm_pass
      POSTGRES_DB: osm_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  importer:
    
