#!/usr/bin/env bash
set -euo pipefail

# has the following featues
# "run:Boot AVD"
# "list:List all AVDs"
# "ls:List all AVDs"
# "theme:Switch between light and dark mode"
# "displaysize:Make everything bigger or smaller"


cmd="${1:-}"

case "$cmd" in
    run)
        echo "run called"
        ;;
    list|ls)
        echo "list called"
        ;;
    theme)
        echo "theme called"
        ;;
    displaysize)
        echo "displaysize called"
        ;;
esac

